window.LAWSUIT_TRACKER_DATA = {
  cases: [
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "org",
      firstReportedYear: 2022,
      perpetrator: "Multiple staff",
      role: "Juvenile facilities abuse claims",
      institution: "LA County Juvenile Facilities / MacLaren Children's Center",
      victims: "6,800+ claims",
      victimsDetail: "LA County's April 2025 announcement said the tentative agreement covered more than 6,800 childhood sexual abuse claims",
      victimCountApprox: 6800,
      outcomeType: "Settlement",
      typeClass: "org",
      typeLabel: "Government / Detention",
      settlementDisplay: "$4.0B",
      settlementDetail: "Tentative LA County settlement announced in April 2025",
      settlementMillionsUsd: 4000,
      timeline: [
        {
          date: "April 4, 2025",
          title: "Tentative $4B deal announced",
          body: "Los Angeles County announced a tentative $4 billion settlement covering 6,786 childhood sexual abuse claims under AB 218, described as the largest municipal sexual abuse settlement in U.S. history at the time.",
          source: "LA County",
        },
        {
          date: "April 29, 2025",
          title: "Board of Supervisors approved the first settlement",
          body: "The Board of Supervisors voted unanimously to approve the first settlement package tied to the April announcement, locking in the county's initial response to thousands of abuse claims.",
          source: "LA County Board action",
        },
        {
          date: "October 17, 2025",
          title: "Second settlement expanded the total",
          body: "A second tentative agreement added $828 million to cover 414 additional claims, pushing the combined exposure to nearly $4.83 billion while the overall claim pool continued to expand.",
          source: "Spectrum News 1",
        },
        {
          date: "Late 2025",
          title: "Fraud allegations disrupted the process",
          body: "An LA Times investigation described alleged claim solicitation and fabricated filings tied to Downtown LA Law Group. The firm denied authorizing improper payments.",
          source: "Los Angeles Times / Knock LA",
        },
        {
          date: "January 2026",
          title: "Payouts paused during criminal review",
          body: "District Attorney Nathan Hochman urged the county to delay distributions while potential fraud was investigated. The county agreed to place hundreds of millions into a settlement trust while withholding payouts.",
          source: "Insurance Journal",
        },
        {
          date: "February 27, 2026",
          title: "Formal investigation into DTLA Law Group",
          body: "County Counsel launched a formal unfair-competition investigation and issued an administrative subpoena. Officials also said total filed and anticipated claims had climbed far beyond the original settlement pool.",
          source: "Los Angeles County",
        },
        {
          date: "Current status",
          title: "Approved settlement, but payments remain frozen",
          body: "The settlement framework exists, but payouts are still effectively on hold while fraud investigations continue and the county pushes for changes to AB 218.",
          source: "Ongoing",
        },
      ],
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "doctor",
      firstReportedYear: 2018,
      perpetrator: "Dr. George Tyndall",
      role: "Gynecologist · 30-yr career",
      institution: "Univ. of Southern California (USC)",
      victims: "16,700+",
      victimsDetail: "16,019 federal claimants + 761 state plaintiffs compensated",
      victimCountApprox: 16780,
      outcomeType: "Settlement",
      typeClass: "doctor",
      typeLabel: "Doctor",
      settlementDisplay: ">$1.1B total",
      settlementDetail: "$852M state court settlement + $215M federal class action + other settlements",
      settlementMillionsUsd: 1100,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "doctor",
      firstReportedYear: 2016,
      perpetrator: "Dr. Larry Nassar",
      role: "Sports physician · ~20-yr career",
      institution: "Michigan State Univ. / USA Gymnastics / USOPC / FBI",
      victims: "500+",
      victimsDetail: "Elite & Olympic athletes",
      victimCountApprox: 500,
      outcomeType: "Settlement",
      typeClass: "doctor",
      typeLabel: "Doctor",
      settlementDisplay: "~$1.02B total",
      settlementDetail: "$500M (MSU) · $380M (USAG/USOPC) · $138.7M (DOJ/FBI)",
      settlementMillionsUsd: 1018.7,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "doctor",
      firstReportedYear: 2012,
      perpetrator: "Dr. Robert Hadden",
      role: "OB-GYN · ~25-yr career",
      institution: "Columbia Univ. / NewYork-Presbyterian Hospital",
      victims: "576+",
      victimsDetail: "Women; 6,500 former patients notified",
      victimCountApprox: 576,
      outcomeType: "Settlement",
      typeClass: "doctor",
      typeLabel: "Doctor",
      settlementDisplay: ">$1B total",
      settlementDetail: "$750M (2025) · $165M · $71.5M · $100M fund",
      settlementMillionsUsd: 1086.5,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "doctor",
      firstReportedYear: 2020,
      perpetrator: "Dr. Robert Anderson",
      role: "Sports physician · 37-yr career",
      institution: "University of Michigan",
      victims: "1,050+",
      victimsDetail: "Mostly male student-athletes",
      victimCountApprox: 1050,
      outcomeType: "Settlement",
      typeClass: "doctor",
      typeLabel: "Doctor",
      settlementDisplay: "$490M",
      settlementDetail: "$460M distributed + $30M future claims fund",
      settlementMillionsUsd: 490,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "doctor",
      firstReportedYear: 2019,
      perpetrator: "Dr. James Heaps",
      role: "Gynecologist / oncologist · 35-yr career",
      institution: "UCLA / UC System",
      victims: "300+",
      victimsDetail: "Women patients 1983–2018",
      victimCountApprox: 300,
      outcomeType: "Settlement",
      typeClass: "doctor",
      typeLabel: "Doctor",
      settlementDisplay: "~$700M total",
      settlementDetail: "$375M (UC system) · $73M class · $243.6M additional",
      settlementMillionsUsd: 691.6,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "doctor",
      firstReportedYear: 2018,
      perpetrator: "Dr. Richard Strauss",
      role: "Sports physician · 20-yr career",
      institution: "Ohio State University",
      victims: "304+",
      victimsDetail: "177 confirmed; 236 men still suing",
      victimCountApprox: 304,
      outcomeType: "Ongoing litigation",
      typeClass: "doctor",
      typeLabel: "Doctor",
      settlementDisplay: "$60M+",
      settlementDisplayClass: "large",
      settlementSuffix: "(ongoing)",
      settlementDetail: "Multiple settlement tranches 2020–2026",
      settlementMillionsUsd: 60,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "doctor",
      firstReportedYear: 2023,
      perpetrator: "Dr. Derrick Todd",
      role: "Rheumatologist · affiliated physician",
      institution: "Brigham and Women's Hospital (affiliated)",
      victims: "200+",
      victimsDetail: "Patients in class action and related civil claims",
      victimCountApprox: 200,
      outcomeType: "Ongoing litigation",
      typeClass: "doctor",
      typeLabel: "Doctor",
      settlementPending: "No final settlement",
      settlementDetail: "Class action remains ongoing",
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "coach",
      firstReportedYear: 2011,
      perpetrator: "Jerry Sandusky",
      role: "Asst. football coach",
      institution: "Penn State University",
      victims: "60+",
      victimsDetail: "Young men; convicted on 45 counts",
      victimCountApprox: 60,
      outcomeType: "Settlement",
      typeClass: "coach",
      typeLabel: "Coach",
      settlementDisplay: "$100M+",
      settlementDetail: "Multiple individual settlements since 2013",
      settlementMillionsUsd: 100,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "coach",
      firstReportedYear: 2018,
      perpetrator: "Bahram Hojreh",
      role: "Water polo coach",
      institution: "USA Water Polo",
      victims: "~12",
      victimsDetail: "Grouped claims by athletes and families",
      victimCountApprox: 12,
      outcomeType: "Settlement",
      typeClass: "coach",
      typeLabel: "Coach",
      settlementDisplay: "~$14M",
      settlementDetail: "Group lawsuit resolved by settlement",
      settlementMillionsUsd: 14,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "coach",
      firstReportedYear: 2020,
      perpetrator: "Herman Hopson",
      role: "Track & field coach",
      institution: "Pomona High School / Pomona USD",
      victims: "Multiple",
      victimsDetail: "Women; abuse in 1990s",
      outcomeType: "Settlement",
      typeClass: "coach",
      typeLabel: "Coach",
      settlementDisplay: "$35M",
      settlementDetail: "Jury award Jan 2024",
      settlementMillionsUsd: 35,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "coach",
      firstReportedYear: 2021,
      perpetrator: "Ronald Gene Akins",
      role: "Basketball coach",
      institution: "Ninnekah Public Schools, Oklahoma",
      victims: "14",
      victimsDetail: "Female students; Akins serving 15 yrs",
      victimCountApprox: 14,
      outcomeType: "Settlement",
      typeClass: "coach",
      typeLabel: "Coach",
      settlementDisplay: "$7.5M",
      settlementDetail: "Settlement 2024",
      settlementMillionsUsd: 7.5,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "coach",
      firstReportedYear: 2021,
      perpetrator: "NWSL coaches & officials",
      role: "Multiple abusers over 10+ years",
      institution: "National Women's Soccer League (NWSL)",
      victims: "Multiple",
      victimsDetail: "Professional players; decade-long pattern",
      outcomeType: "Settlement",
      typeClass: "coach",
      typeLabel: "Coach / Org",
      settlementDisplay: "$5M",
      settlementDetail: "Feb 2025 AG settlement; +$2M penalty if non-compliant",
      settlementMillionsUsd: 5,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "coach",
      firstReportedYear: 2021,
      perpetrator: "UNCSA staff",
      role: "Teachers & administrators",
      institution: "Univ. of North Carolina School of the Arts",
      victims: "65",
      victimsDetail: "Alumni; decades of abuse",
      victimCountApprox: 65,
      outcomeType: "Settlement",
      typeClass: "coach",
      typeLabel: "School Staff",
      settlementDisplay: "$12.5M",
      settlementDetail: "Settlement May 2024",
      settlementMillionsUsd: 12.5,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "org",
      firstReportedYear: 2010,
      perpetrator: "Multiple scout leaders",
      role: "Youth organization abuse",
      institution: "Boy Scouts of America (BSA)",
      victims: "82,000+",
      victimsDetail: "Men; abuse spanning decades",
      victimCountApprox: 82000,
      outcomeType: "Settlement",
      typeClass: "org",
      typeLabel: "Youth Org",
      settlementDisplay: "$2.46B",
      settlementDetail: "Largest single sex-abuse settlement in US history (2023)",
      settlementMillionsUsd: 2460,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "church",
      firstReportedYear: 2002,
      perpetrator: "Multiple clergy",
      role: "Priests; decades of abuse",
      institution: "Archdiocese of Los Angeles",
      victims: "1,353",
      victimsDetail: "Children and young adults",
      victimCountApprox: 1353,
      outcomeType: "Settlement",
      typeClass: "church",
      typeLabel: "Clergy",
      settlementDisplay: "$880M",
      settlementDetail: "Oct 2024; prior $740M = $1.5B+ total to date",
      settlementMillionsUsd: 880,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "church",
      firstReportedYear: 2002,
      perpetrator: "Multiple clergy",
      role: "Catholic archdiocese abuse claims",
      institution: "Archdiocese of Boston",
      victims: "552",
      victimsDetail: "2003 settlement covered 552 victims in more than 500 abuse claims",
      victimCountApprox: 552,
      outcomeType: "Settlement",
      typeClass: "church",
      typeLabel: "Church / Clergy",
      settlementDisplay: "$85M",
      settlementDetail: "Boston archdiocese settlement finalized in 2003",
      settlementMillionsUsd: 85,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "church",
      firstReportedYear: 2000,
      perpetrator: "Multiple clergy",
      role: "Bankruptcy abuse settlement",
      institution: "Diocese of Rockville Centre, New York",
      victims: "600+",
      victimsDetail: "Bankruptcy settlement resolved abuse claims involving more than 600 survivors",
      victimCountApprox: 600,
      outcomeType: "Settlement",
      typeClass: "church",
      typeLabel: "Church / Clergy",
      settlementDisplay: "$323M",
      settlementDetail: "Bankruptcy settlement made official in December 2024",
      settlementMillionsUsd: 323,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "org",
      firstReportedYear: 2005,
      perpetrator: "Jeffrey Epstein",
      role: "Sex trafficking and estate compensation claims",
      institution: "Epstein Estate / associated financial facilitators",
      victims: "150+ VCP claimants",
      victimsDetail: "Victims compensation program paid 150 claimants; additional settlements continued in 2026",
      victimCountApprox: 150,
      outcomeType: "Settlement",
      typeClass: "org",
      typeLabel: "Sex Trafficking",
      settlementDisplay: "$205M+",
      settlementDetail: "$121M VCP + $49M prior estate settlements + up to $35M 2026 class-action agreement",
      settlementMillionsUsd: 205,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "org",
      firstReportedYear: 2017,
      perpetrator: "Harvey Weinstein",
      role: "Entertainment workplace abuse claims",
      institution: "The Weinstein Company",
      victims: "80+ accusers",
      victimsDetail: "Class-action settlement fund created for women alleging harassment and abuse",
      victimCountApprox: 80,
      outcomeType: "Settlement",
      typeClass: "org",
      typeLabel: "Entertainment / Workplace",
      settlementDisplay: "$18.875M",
      settlementDetail: "Federal class-action settlement announced in 2020 and approved in 2021",
      settlementMillionsUsd: 18.875,
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "church",
      firstReportedYear: 2022,
      perpetrator: "LDS church bishops (cover-up)",
      role: "Failure-to-report abuse case",
      institution: "Church of Jesus Christ of Latter-day Saints",
      victims: "1 verdict plaintiff",
      victimsDetail: "Case centered on one plaintiff alleging years of abuse and institutional failure to report",
      victimCountApprox: 1,
      outcomeType: "Jury verdict",
      typeClass: "church",
      typeLabel: "Church / Clergy",
      settlementPending: "$2.28B verdict",
      settlementDetail: "AP reported a $2.28B verdict; church had separately settled its portion for about $1M before verdict",
    },
    {
      countryCode: "can",
      countryLabel: "Canada",
      category: "org",
      firstReportedYear: 2017,
      perpetrator: "Dave Brubaker",
      role: "Team Canada head coach",
      institution: "Gymnastics Canada / Bluewater Gymnastics Club",
      victims: "11",
      victimsDetail: "Gymnasts filed a complaint in 2019",
      victimCountApprox: 11,
      outcomeType: "Disciplinary outcome",
      typeClass: "org",
      typeLabel: "Sports Org",
      settlementPending: "No settlement disclosed",
      settlementDetail: "Acquitted criminally; later banned for life after 54 allegations were found credible",
    },
    {
      countryCode: "uk",
      countryLabel: "UK",
      category: "org",
      firstReportedYear: 2020,
      perpetrator: "British Gymnastics group claim",
      role: "Physical and psychological abuse allegations",
      institution: "British Gymnastics",
      victims: "37+",
      victimsDetail: "17 claimants at filing; 20 more joined by March 2021",
      victimCountApprox: 37,
      outcomeType: "Ongoing litigation",
      typeClass: "org",
      typeLabel: "Sports Org",
      settlementPending: "No settlement disclosed",
      settlementDetail: "Group legal action sought compensation and safeguarding reforms",
    },
    {
      countryCode: "can",
      countryLabel: "Canada",
      category: "org",
      firstReportedYear: 2019,
      perpetrator: "Francois Lamarre",
      role: "Minor hockey coach",
      institution: "Quebec minor hockey organizations",
      victims: "Dozens",
      victimsDetail: "Class action by former youth players",
      outcomeType: "Settlement",
      typeClass: "org",
      typeLabel: "Sports Org",
      settlementDisplay: "~C$10.25M",
      settlementDetail: "Class action settlement approved in Quebec",
    },
    {
      countryCode: "uk",
      countryLabel: "UK",
      category: "org",
      firstReportedYear: 2017,
      perpetrator: "Celtic Boys Club abuse",
      role: "Youth football coaches and staff",
      institution: "Celtic Football Club",
      victims: "20+",
      victimsDetail: "Grouped claims in Scottish proceedings",
      victimCountApprox: 20,
      outcomeType: "Settlement",
      typeClass: "org",
      typeLabel: "Sports Org",
      settlementPending: "Five-figure sum (GBP)",
      settlementDetail: "BBC reported one claimant accepted a five-figure-pound settlement",
    },
    {
      countryCode: "can",
      countryLabel: "Canada",
      category: "org",
      firstReportedYear: 2005,
      perpetrator: "Multiple clergy and government staff",
      role: "Residential schools redress",
      institution: "Indian Residential Schools system",
      victims: "~80,000 survivors compensated",
      victimsDetail: "IRSSA covered former students across the residential school system",
      victimCountApprox: 80000,
      outcomeType: "Settlement",
      typeClass: "org",
      typeLabel: "Government / Church",
      settlementDisplay: "C$1.9B+",
      settlementDetail: "IRSSA common-experience compensation package; later additional compensation streams expanded the total further",
    },
    {
      countryCode: "bra",
      countryLabel: "Brazil",
      category: "coach",
      firstReportedYear: 2018,
      perpetrator: "Fernando de Carvalho Lopes",
      role: "National coach",
      institution: "Brazil national gymnastics program / Clube MESC",
      victims: "40 alleged",
      victimsDetail: "Formal charges were laid regarding 4 victims",
      victimCountApprox: 40,
      outcomeType: "Criminal conviction",
      typeClass: "coach",
      typeLabel: "Coach",
      settlementPending: "Criminal only",
      settlementDetail: "Banned for life in 2022; sentenced to 109 years and 8 months in prison",
    },
    {
      countryCode: "fra",
      countryLabel: "France",
      category: "org",
      firstReportedYear: 2017,
      perpetrator: "Joel Le Scouarnec",
      role: "Surgeon in public hospitals",
      institution: "French public hospital system",
      victims: "299",
      victimsDetail: "Primarily a criminal case with related civil exposure",
      victimCountApprox: 299,
      outcomeType: "Criminal case",
      typeClass: "org",
      typeLabel: "Hospital System",
      settlementPending: "Primarily criminal",
      settlementDetail: "Criminal proceedings ongoing; civil claims remain secondary",
    },
    {
      countryCode: "aus",
      countryLabel: "Australia",
      category: "org",
      firstReportedYear: 1995,
      perpetrator: "AIS / Opie report",
      role: "Program-level abuse allegations",
      institution: "Australian Institute of Sport (WAG program)",
      victims: "3 known complainants",
      victimsDetail: "One alleged physical assault case and two emotional-abuse complaints triggered the review",
      victimCountApprox: 3,
      outcomeType: "Investigation / review",
      typeClass: "org",
      typeLabel: "Sports Institute",
      settlementPending: "No abuse finding",
      settlementDetail: "1995 independent inquiry found no systematic abuse and recommended limited corrective action",
    },
    {
      countryCode: "aus",
      countryLabel: "Australia",
      category: "church",
      firstReportedYear: 2013,
      perpetrator: "Multiple clergy and staff",
      role: "Royal Commission claims data",
      institution: "Catholic Church Australia",
      victims: "4,444 claimants",
      victimsDetail: "Royal Commission data covered allegations made to 93 Catholic authorities from 1980 to 2015",
      victimCountApprox: 4444,
      outcomeType: "Cumulative settlements",
      typeClass: "church",
      typeLabel: "Church / Institution",
      settlementDisplay: "$200M+",
      settlementDetail: "Britannica summarized Catholic Church payouts in Australia from 1980 to 2017 at more than $200M",
    },
    {
      countryCode: "aus",
      countryLabel: "Australia",
      category: "coach",
      firstReportedYear: 2003,
      perpetrator: "Geoffery Robert Dobbs",
      role: "Gymnastics coach",
      institution: "Australian gymnastics clubs",
      victims: "62 convicted / 300+ suspected",
      victimsDetail: "Life sentence followed convictions involving girls aged 12 months to 15 years",
      victimCountApprox: 62,
      outcomeType: "Criminal conviction",
      typeClass: "coach",
      typeLabel: "Coach",
      settlementPending: "Life sentence",
      settlementDetail: "Sentenced in 2003 to life imprisonment with no prospect of parole",
    },
    {
      countryCode: "aus",
      countryLabel: "Australia",
      category: "org",
      firstReportedYear: 2024,
      perpetrator: "WAIS WAG program review",
      role: "Athlete welfare and abuse allegations",
      institution: "Western Australian Institute of Sport",
      victims: "Not quantified",
      victimsDetail: "SIA review found some gymnasts likely suffered abuse or harm",
      outcomeType: "Investigation / review",
      typeClass: "org",
      typeLabel: "Sports Institute",
      settlementPending: "Formal apology",
      settlementDetail: "2022 review led to apology, governance review, and safeguarding reforms rather than a civil settlement",
    },
    {
      countryCode: "irl",
      countryLabel: "Ireland",
      category: "church",
      firstReportedYear: 2009,
      perpetrator: "Multiple clergy and religious orders",
      role: "Institutional abuse redress",
      institution: "Catholic Church Ireland / Ryan Report era institutions",
      victims: "15,579 awards / 2,000+ institutional survivors",
      victimsDetail: "Irish redress scheme and inquiry costs reached about €1.5B by end-2015",
      victimCountApprox: 15579,
      outcomeType: "Settlement",
      typeClass: "church",
      typeLabel: "Church / Government",
      settlementDisplay: "€1.5B",
      settlementDetail: "Redress Board and inquiry costs reached about €1.5B by end-2015, including €1.25B in awards",
    },
    {
      countryCode: "can",
      countryLabel: "Canada",
      category: "coach",
      firstReportedYear: 2019,
      perpetrator: "Alex Bard",
      role: "National WAG team coach",
      institution: "Gymnastics Canada",
      victims: "Multiple",
      victimsDetail: "Misconduct reports included kissing young gymnasts and inappropriate touching",
      outcomeType: "Resignation / allegations",
      typeClass: "coach",
      typeLabel: "Coach",
      settlementPending: "No settlement disclosed",
      settlementDetail: "Resigned in 2019 after misconduct concerns; later criticism focused on governance failure and lack of oversight",
    },
    {
      countryCode: "can",
      countryLabel: "Canada",
      category: "coach",
      firstReportedYear: 2021,
      perpetrator: "Marcel Rene",
      role: "Coach and gym owner",
      institution: "Champion Gymnastics / Gymnastics Ontario",
      victims: "2 named plaintiffs",
      victimsDetail: "Two women named in civil actions filed in November 2020 and January 2021 alleging workplace sexual harassment",
      victimCountApprox: 2,
      typeClass: "coach",
      typeLabel: "Coach",
      
      settlementPending: "Lifetime suspension",
      settlementDetail: "Gymnastics Ontario barred Rene from coaching, field-of-play activities, and club operations effective 2022",
      timeline: [
        {
          date: "November 2020",
          title: "First civil action filed",
          body: "One former employee filed a civil action against Marcel Rene and Champion Gymnastics alleging workplace sexual harassment.",
          source: "News.txt / kawarthaNOW",
        },
        {
          date: "January 2021",
          title: "Second civil action followed",
          body: "A second woman filed a related civil action alleging sexual harassment in the workplace.",
          source: "News.txt / kawarthaNOW",
        },
        {
          date: "November 1, 2021",
          title: "Lifetime suspension announced",
          body: "Gymnastics Ontario announced that Rene had received a lifetime suspension, initially set to take effect on January 1, 2022.",
          source: "News.txt / Peterborough Examiner",
        },
        {
          date: "November 5, 2021",
          title: "Immediate interim suspension imposed",
          body: "After media reports and the release of civil-court and ethics-investigation documents, Gymnastics Ontario placed Rene under immediate interim suspension.",
          source: "News.txt / kawarthaNOW",
        },
        {
          date: "April 4, 2022",
          title: "National abuse reporting referenced the case",
          body: "Canadian Press listed Rene among coaches who had been suspended amid broader scrutiny of abuse and maltreatment in Canadian gymnastics, noting the reasons for his suspension had not been publicly explained by the association.",
          source: "News.txt / Canadian Press",
        },
      ],
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "org",
      firstReportedYear: 2023,
      perpetrator: "Mike Jeffries",
      role: "Former CEO accused in sex-trafficking enterprise",
      institution: "Abercrombie & Fitch / Jeffries-linked sex events",
      victims: "15 charged accusers",
      victimsDetail: "Federal sex-trafficking case names 15 accusers; competency proceedings continued in March 2026",
      outcomeType: "Criminal case",
      typeClass: "org",
      typeLabel: "Corporate / Trafficking",
      settlementPending: "Pending",
      settlementDetail: "Federal criminal case remains pending after 2024 charges and 2026 competency proceedings",
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "org",
      firstReportedYear: 2022,
      perpetrator: "Gregory Rodriguez + others",
      role: "Prison staff abuse lawsuits",
      institution: "Central California Women's Facility / CDCR",
      victims: "500+ suits",
      victimsDetail: "Hundreds of prison-abuse lawsuits tied to Chowchilla and other California women's prisons",
      victimCountApprox: 500,
      outcomeType: "Ongoing litigation",
      typeClass: "org",
      typeLabel: "Prison / Government",
      settlementPending: "Pending",
      settlementDetail: "Wave of prison-abuse litigation remains active while separate criminal convictions and some individual settlements proceed",
    },
    {
      countryCode: "usa",
      countryLabel: "USA",
      category: "church",
      firstReportedYear: 2004,
      perpetrator: "Multiple Catholic clergy",
      role: "Nationwide cumulative allegations and payouts",
      institution: "US Catholic Church (nationwide)",
      victims: "16,276 credible allegations",
      victimsDetail: "CARA reported 16,276 credible allegations from 2004 to 2023 across dioceses and men's religious communities",
      victimCountApprox: 16276,
      outcomeType: "Cumulative settlements",
      typeClass: "church",
      typeLabel: "Church / Clergy",
      settlementDisplay: "$5.025B",
      settlementDetail: "CARA reported more than $5B spent from 2004 to 2023 on abuse allegations in the U.S.",
      settlementMillionsUsd: 5025,
    },
  ],
};

const CASE_ENRICHMENT = {
  "LA County Juvenile Facilities / MacLaren Children's Center|Multiple staff": {
    perpetratorGender: "multiple",
    coverUpFinding: null,
  },
  "Univ. of Southern California (USC)|Dr. George Tyndall": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: 43,
    perpetratorAgeWhenCaught: 72,
    coverUpFinding: "documented",
  },
  "Michigan State Univ. / USA Gymnastics / USOPC / FBI|Dr. Larry Nassar": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: 29,
    perpetratorAgeWhenCaught: 53,
    coverUpFinding: "documented",
  },
  "Columbia Univ. / NewYork-Presbyterian Hospital|Dr. Robert Hadden": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: 33,
    perpetratorAgeWhenCaught: 52,
    coverUpFinding: "documented",
  },
  "University of Michigan|Dr. Robert Anderson": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: 37,
    perpetratorAgeWhenCaught: null,
    coverUpFinding: "documented",
  },
  "UCLA / UC System|Dr. James Heaps": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: 62,
    coverUpFinding: "documented",
  },
  "Ohio State University|Dr. Richard Strauss": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: 20,
    perpetratorAgeWhenCaught: 81,
    coverUpFinding: "documented",
  },
  "Brigham and Women's Hospital (affiliated)|Dr. Derrick Todd": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: null,
    coverUpFinding: "alleged",
  },
  "Penn State University|Jerry Sandusky": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: 50,
    perpetratorAgeWhenCaught: 67,
    coverUpFinding: "documented",
  },
  "USA Water Polo|Bahram Hojreh": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: null,
    coverUpFinding: "alleged",
  },
  "Pomona High School / Pomona USD|Herman Hopson": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: null,
    coverUpFinding: null,
  },
  "Ninnekah Public Schools, Oklahoma|Ronald Gene Akins": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: null,
    coverUpFinding: null,
  },
  "National Women's Soccer League (NWSL)|NWSL coaches & officials": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "Univ. of North Carolina School of the Arts|UNCSA staff": {
    perpetratorGender: "multiple",
    coverUpFinding: "alleged",
  },
  "Boy Scouts of America (BSA)|Multiple scout leaders": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "Archdiocese of Los Angeles|Multiple clergy": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "Archdiocese of Boston|Multiple clergy": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "Diocese of Rockville Centre, New York|Multiple clergy": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "Epstein Estate / associated financial facilitators|Jeffrey Epstein": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: 43,
    perpetratorAgeWhenCaught: 52,
    coverUpFinding: "documented",
  },
  "The Weinstein Company|Harvey Weinstein": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: 65,
    coverUpFinding: "alleged",
  },
  "Church of Jesus Christ of Latter-day Saints|LDS church bishops (cover-up)": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "Gymnastics Canada / Bluewater Gymnastics Club|Dave Brubaker": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: null,
    coverUpFinding: null,
  },
  "British Gymnastics|British Gymnastics group claim": {
    perpetratorGender: "multiple",
    coverUpFinding: "alleged",
  },
  "Quebec minor hockey organizations|Francois Lamarre": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: null,
    coverUpFinding: null,
  },
  "Celtic Football Club|Celtic Boys Club abuse": {
    perpetratorGender: "multiple",
    coverUpFinding: "alleged",
  },
  "Indian Residential Schools system|Multiple clergy and government staff": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "Brazil national gymnastics program / Clube MESC|Fernando de Carvalho Lopes": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: null,
    coverUpFinding: "alleged",
  },
  "French public hospital system|Joel Le Scouarnec": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: 38,
    perpetratorAgeWhenCaught: 66,
    coverUpFinding: "documented",
  },
  "Australian Institute of Sport (WAG program)|AIS / Opie report": {
    perpetratorGender: "multiple",
    coverUpFinding: null,
  },
  "Catholic Church Australia|Multiple clergy and staff": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "Australian gymnastics clubs|Geoffery Robert Dobbs": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: null,
    coverUpFinding: null,
  },
  "Western Australian Institute of Sport|WAIS WAG program review": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "Catholic Church Ireland / Ryan Report era institutions|Multiple clergy and religious orders": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "Gymnastics Canada|Alex Bard": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: null,
    coverUpFinding: "alleged",
  },
  "Champion Gymnastics / Gymnastics Ontario|Marcel Rene": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: 71,
    coverUpFinding: null,
  },
  "Abercrombie & Fitch / Jeffries-linked sex events|Mike Jeffries": {
    perpetratorGender: "male",
    perpetratorAgeAtFirstOffense: null,
    perpetratorAgeWhenCaught: 79,
    coverUpFinding: "alleged",
  },
  "Central California Women's Facility / CDCR|Gregory Rodriguez + others": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
  "US Catholic Church (nationwide)|Multiple Catholic clergy": {
    perpetratorGender: "multiple",
    coverUpFinding: "documented",
  },
};

window.LAWSUIT_TRACKER_DATA.cases = window.LAWSUIT_TRACKER_DATA.cases.map((item) => {
  const key = `${item.institution}|${item.perpetrator}`;
  const meta = CASE_ENRICHMENT[key] || {};
  const settlementPerVictimUsd =
    typeof item.settlementMillionsUsd === "number" &&
    typeof item.victimCountApprox === "number" &&
    item.victimCountApprox > 0
      ? Math.round((item.settlementMillionsUsd * 1000000) / item.victimCountApprox)
      : null;

  const ageAtFirstOffense =
    typeof meta.perpetratorAgeAtFirstOffense === "number"
      ? meta.perpetratorAgeAtFirstOffense
      : null;
  const ageWhenCaught =
    typeof meta.perpetratorAgeWhenCaught === "number"
      ? meta.perpetratorAgeWhenCaught
      : null;

  return {
    ...item,
    perpetratorGender: meta.perpetratorGender ?? null,
    perpetratorAgeAtFirstOffense: ageAtFirstOffense,
    perpetratorAgeWhenCaught: ageWhenCaught,
    yearsActiveBeforeCaught:
      typeof ageAtFirstOffense === "number" && typeof ageWhenCaught === "number"
        ? ageWhenCaught - ageAtFirstOffense
        : null,
    coverUpFinding: meta.coverUpFinding ?? null,
    settlementPerVictimUsd,
  };
});
